### ISSUE TITLE
Add Granular Certification Use Case

### ISSUE THREAD

**Issue by halliecramer1** [carbon-data-specification/Customer-Data#8]
Use Case 2: Decarbonization Projects

Needs:
...
Granular Certification Data Access: Granular certificates are an important decarbonization tool for applications such as tracking 24/7 carbon-free energy matching and creating market signals to stimulate investment in new clean technologies. Granular certification depends on streamlined and scalable access to granular generation data from clean energy projects (for example, from wholesale power purchase agreements). To address this use case, the specifications must consider how to obtain (revenue grade) metered generation data from individual asset owners in a centralized and secure manner.
...

Not in scope: Registry data integrations

**Comment by daniel-utilityapi** [comment]
@halliecramer1 I've opened a pull request for review with your proposed language.

Some changes:
1. I put the need in Use Case 1, which is inherited by Use Case 2 and 3. Wouldn't this data type be helpful for all of the first three Use Cases (carbon accounting, decarbonization projects, and grid flexibility)?
2. I reworded your suggested not-in-scope, since I didn't really know what you meant by "Registry data integrations". Can you please review my rewording? Also, in the other not-in-scope items, I try to give examples. Can you please add some examples to the pull request in-line comments?

@saflexidao I'm not sure I'm following your comment. Are you talking about distributed storage? I don't know the acronyms you're using. Could you please expand them? Thanks!

**Comment by daniel-utilityapi** [comment]
Merged!
